<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE menu [<!ELEMENT menu (menuGroup*, menuLink*)*>

<!ELEMENT menuGroup (menuGroup*|menuLink+)+>
<!ELEMENT menuLink (#PCDATA)>


<!ATTLIST menuGroup key CDATA #REQUIRED>
<!ATTLIST menuGroup label CDATA #REQUIRED>

<!ATTLIST menuLink key CDATA #REQUIRED>
<!ATTLIST menuLink label CDATA #REQUIRED>
<!ATTLIST menuLink mode CDATA #REQUIRED>
<!ATTLIST menuLink windowname CDATA #REQUIRED>
<!ATTLIST menuLink module CDATA #REQUIRED>]><menu><menuGroup key="BankCustomerHibernate_GUI" label="BankCustomerHibernate_GUI">
    <menuLink label="Create Hibernate"  key="BankCustomerHibernate_GUI.CreateHibernate" windowname="CreateHibernate" module="BankCustomerHibernate_GUI"  mode="DEFAULT"/>
</menuGroup >
</menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu></menu>